controller_manager:
ros__parameters:
update_rate: 30
use_sim_time: true
diff_cont:
type: "diff_drive_controller/DiffDriveController"
ros__parameters:
publish_rate: 50
base_frame_id: base_link
left_wheel: 'lwheel'
right_wheel: 'rwheel'
wheel_separation: 0.18
wheel_radius: 0.022s
cmd_vel_timout: 0.25
#use_stamped_vel: false

#joint_bradcast:
#type: "joint_staet_bradcaster/JointStateBroadcaster"
#	diff_cont:
#		ros__parameters:
#btechbot:
# joint_vel_controller:
# type: "joint_velocity_controller/JointVelocityController"
# left_joint: "lwheel"
# right_joint: "rwheel"
# pid:
# p: 100.0
# i: 0.1
# d: 10.0


#joint_state_controller:
# type: "joint_state_controller/JointStateController"
# publish_rate: 50

#left_wheel_controller:
# type: diff_drive_controller/DiffDriveController
# left_wheel: lwheel
# right_wheel: rwheel
# wheel_separation: 0.18
# wheel_radius: 0.022
# publish_rate: 50

#right_wheel_controller:
# type: diff_drive_controller/DiffDriveController
# left_wheel: lwheel
# right_wheel: rwheel
# wheel_separation: 0.18
# wheel_radius: 0.022
# publish_rate: 50

# robot_state_publisher:
# type: robot_state_publisher/RobotStatePublisher

